In [1]:
import pandas as pd

In [ ]:
# pandas has two core obj ects: Series and DataFrame

In [4]:
#series 
pd.Series((1, 2, 3,),name="Age")

0    1
1    2
2    3
Name: Age, dtype: int64

In [5]:
# dataframe
#dictionary of series
di={"name": ["shikhar","mango","pen", "mobile"],
    "identity": ["human","fruit","stationary","electronic"]
}
df=pd.DataFrame(di)

In [7]:
print(type(df))

<class 'pandas.DataFrame'>

In [9]:
df.head(2)

      name identity
0  shikhar    human
1    mango    fruit

In [10]:
df.tail(2)

     name    identity
2     pen  stationary
3  mobile  electronic

In [12]:
df.sample(2)

     name    identity
3  mobile  electronic
1   mango       fruit

In [13]:
df.head()

      name    identity
0  shikhar       human
1    mango       fruit
2      pen  stationary
3   mobile  electronic

In [ ]:
count=[1,10,3,2]
df.insert(0,"count",count)

In [17]:
df

   count     name    identity
0      1  shikhar       human
1     10    mango       fruit
2      3      pen  stationary
3      2   mobile  electronic

In [24]:
colour = "skin","orange","blue","black"

In [26]:
df[colour] =colour

In [27]:
df["id"] = [1,2,3,4]

In [28]:
df.sample()

   count    name    identity (skin, orange, blue, black)  id
3      2  mobile  electronic                       black   4

In [38]:
# new dataframe df2 id, weight
df2 = pd.DataFrame({"id":[1,2,6,4,5],
"weight":[50,60,70,80,None ]})

print(df2)

   id  weight
0   1    50.0
1   2    60.0
2   6    70.0
3   4    80.0
4   5     NaN

In [43]:
#merge 
pd.merge(df,df2, how="right" , on="id")

   count     name    identity (skin, orange, blue, black)  id  weight
0    1.0  shikhar       human                        skin   1    50.0
1   10.0    mango       fruit                      orange   2    60.0
2    NaN      NaN         NaN                         NaN   6    70.0
3    2.0   mobile  electronic                       black   4    80.0
4    NaN      NaN         NaN                         NaN   5     NaN